apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-scheduler
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-cppm
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: scheduler
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
      - values/global-values.yaml
      - values.yaml
      values: |-
        global:
          nfs:
            natIp: 169.254.170.73