apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "common.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "common.image" . }}
          args: [/bin/sh, -c, '/opt/ahnlab/cpp/cmd/epp-tomcat-agent.sh']
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
#            - name: tcp-external
#              containerPort: 8804
#              protocol: TCP
            - name: tcp
              containerPort: 8807
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /
#              port: tcp-external
#          readinessProbe:
#            httpGet:
#              path: /
#              port: tcp-external
          resources: {{- include "common.resources" . | nindent 12 }}
          {{- with .Values.global.volumeMounts }}
          volumeMounts:
          - name: {{ include "common.fullname" $ }}-applog
            mountPath: /permanent/log/agent
            {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- if .Values.logSideCar.enabled }}
        - name: log-side-car
          image: busybox:1.28
          args: [/bin/sh, -c, 'tail -n+1 -F /var/log/{{ .Chart.Name }}_server.log']
          volumeMounts:
          - name: {{ include "common.fullname" . }}-applog
            mountPath: /var/log
          resources: {{- include "logSideCar.resources" . | nindent 12 }}
        {{- end }}
      volumes:
      - name: {{ include "common.fullname" . }}-applog
        emptyDir: {}
      {{- if .Values.global.nfs.enabled }}
      {{- range .Values.global.volumes }}
      - name: {{ .name | quote }}
        {{- with .configMap}}
        configMap:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .nfs }}
        nfs:
          path: {{ .path | quote }}
          server: {{ $.Values.global.nfs.natIp }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
